models:
  - name: dim_listings_cleansed
    description: Cleansed table that contains airbnb listings
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000000000
          #severity: warn
          severity: error
    columns:
      - name: listing_id 
        description: Primary key for listing
        data_tests:
          - unique 
          - not_null

      - name: host_id
        description: The host's id references hosts table
        data_tests:
          - not_null 
          - relationships: 
              arguments: 
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values

      - name: room_type
        description: Type of apartment/room
        data_tests:
          - accepted_values: 
              arguments: 
                values: ['Entire home/apt','Private room','Shared room','Hotel room']


  - name: dim_hosts_cleansed 
    config:
      contract:
        enforced: True
    columns: 
      - name: host_id 
        data_type: integer
      - name: host_name
        description: '{{ doc("dim_hosts_cleansed__host_name") }}'
        data_type: string
      - name: is_superhost 
        data_type: string
      - name: updated_at
        data_type: timestamp
      - name: created_at
        data_type: timestamp